### ISSUE TITLE
Add feature for node characteristic application

### ISSUE THREAD

**Issue by Entenwilli** [DataFlowAnalysis/PCM-DataFlowAnalysis-Extension#5]
The new method of node characteristic application is currently not deployed on the update site. A entry in the `feature` directory should be added

**Comment by Entenwilli** [comment]
Already addressed in #3

**Comment by Nicolas-Boltz** [comment]
@Entenwilli this is still missing in the main branch! Somewhere along the line, this has gone missing...
We need this to not overcomplicate the use of the nodecharacteristics plugins (as it is currently done with the product). 
The respective folder already exists but there is no content in it.

There should be threethings:
1. A feature that includes the nodecharacterisitics plugin and the respective editors (/org.palladiosimulator.dataflow.confidentiality.pcm.nodecharacteristics.feature/)
2. This feature should be included in the other model and tree.editor features (as it had been done here https://github.com/DataFlowAnalysis/PCM-DataFlowAnalysis-Extension/pull/3/files)
3. This feature should be included in the feature containing everything (https://github.com/DataFlowAnalysis/PCM-DataFlowAnalysis-Extension/tree/main/features/org.palladiosimulator.dataflow.confidentiality.pcm.feature) -> this somehow is not deployed currently, so we need to look into this in the future.
